---
name: publish-global-state-update-gen

on:
  workflow_dispatch:
    branches:
      dev

jobs:
  publish_deb:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            code_name: bionic
          - os: ubuntu-20.04
            code_name: focal

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c #v1.4.0

      - name: Install deps
        run: |
          echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list.d/aptly.list
          wget -qO - https://www.aptly.info/pubkey.txt | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y awscli aptly=1.2.0
          aptly config show

      - name: Install cargo deb
        run: cargo install cargo-deb

      - name: Cargo build
        run: cargo build -p global-state-update-gen --release
